export const PARKING_LOT_DETAILS = "PARKING_LOT/DETAILS";
export const PARKING_SLOT_TYPE = "PARKING_LOT/SLOT/TYPE";
export const NEAREST_PARKING_SLOT = "PARKING_SLOT/NEAREST";
export const ENTRANCE = "ENTRANCE";
export const OBSTACLE = "OBSTACLE";
export const SLOT = "SLOT";
